config/routes.rb
LunchOrder::Application.routes.draw do

  resources :holidays

  resources :line_items

  get "password_resets/new"
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :categories
  resources :menus
  resources :regions
  resources :departments
  resources :orders
  resources :users do
    collection do
      get 'time_cards'
    end
    member do
      get 'time_card'
      post 'download_time_card'
      get 'edit_password'
      put 'update_password'
      put "request_holiday"
      put "unrequest_holiday"
    end
  end
  resources :work_records do
  collection do
    get 'attendance'
  end
end
  resources :sessions
  resources :password_resets
  root :to => 'sessions#new'
  
  #get 'admin' => 'admin#index'
  
  #get 'logout', to: 'sessions#destroy', as: 'logout'

  
  namespace :admin do
  
    
    root :to => 'sessions#new'
    get "menus/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    resources :categories
    resources :users do
      collection do
        get 'time_cards'
      end
      member do
        get 'time_card'
        post 'download_time_card'
        get 'edit_password'
        put 'update_password'
        put "request_holiday"
        put "unrequest_holiday"
      end
    end
    resources :work_records do
      member do
        post 'approve'
        post 'suspend'
      end
      collection do
        get 'monthly'
      end
    end
    resources :menus do
      member do
        put 'toggle'
      end
    end
    resources :regions
    resources :departments
    resources :orders do
    member do
      get 'approve'
    end
  end
    resources :sessions
    resources :searches
    scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
      resources :menus
      root to: 'menus#index'
    end
    match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
    match '', to: redirect("/#{I18n.default_locale}")
  end 
  
  namespace :kitchen do
    root :to => 'sessions#new'
    get "menus/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    resources :categories
    resources :users
    resources :menus do
      member do
        put 'toggle'
      end
    end
    resources :regions
    resources :orders
    resources :sessions
    resources :searches
  end
  
end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  attr_accessible :holiday, :user_id
  validate :not_past_month
  validate :exist_order  
  
  belongs_to :user
	
  def exist_order
    @holidays = Holiday.where('user_id' => self.user_id).where('holiday' => self.holiday)
   
    if @holidays.size > 0
      errors.add(:holiday, "You have already taken holidays for that month")
    end
  end
  
  def not_past_month
    if self.holiday < Date.today.beginning_of_month
      errors.add(:holiday, 'You can choose only a future month')
    end
  end
  
  def user_name
    user.try(:name)
  end

  def user_name=(name)
    self.user = Holiday.find_or_create_by_name(name) if name.present?
  end
  
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.where('user_id' => current_user.id).order('holiday DESC').page(params[:page]).per(15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @holidays }
    end
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
    @holiday = Holiday.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @holiday }
    end
  end

  # GET /holidays/new
  # GET /holidays/new.json
  def new
    @holiday = Holiday.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @holiday }
    end
  end

  # GET /holidays/1/edit
  def edit
    @holiday = Holiday.find(params[:id])
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(params[:holiday])

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render json: @holiday, status: :created, location: @holiday }
      else
        format.html { render action: "new" }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /holidays/1
  # PUT /holidays/1.json
  def update
    @holiday = Holiday.find(params[:id])

    respond_to do |format|
      if @holiday.update_attributes(params[:holiday])
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday = Holiday.find(params[:id])
    @holiday.destroy

    respond_to do |format|
      format.html { redirect_to holidays_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<% if @holiday.errors[:base].size > 0 %>
    <div id="error_explanation" style="width: 800px;">
      <ul>
        <% @holiday.errors[:base].each do |msg| %>
        <li><%= msg %></li>
		<% end %>
      </ul>
    </div>
  <% end %>
<%= simple_form_for @holiday, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Holiday</legend>


    <p>Employee: <b><%= current_user.name %></b></p>
	<%= f.input :holiday, :order => [:month,:year]  %>
	<%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %> 
	

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', orders_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/holidays/edit.html.erb
<%= render 'form' %>

app/views/holidays/index.html.erb
<h2>Holidays</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Employee</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.holiday.strftime("%b-%Y") %></td>
		<td><%= holiday.user_name %></td>
       
        <td>
          <%= link_to (t "holidays.edit"), edit_holiday_path(holiday), :class => 'btn btn-mini' %>
          <%= link_to (t "holidays.destroy"), holiday_path(holiday), :method => :delete, :style => 'color: white', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to (t "orders.new"), new_holiday_path, :style => 'color: white', :class => 'btn btn-primary' %>

app/views/holidays/new.html.erb
<%= render 'form' %>

app/views/holidays/show.html.erb
<h2>Holiday</h2>

<p>
  <b>Date:</b>
  <%= @holiday.holiday.strftime("%b-%Y") %>
</p>

<div class="form-actions">
  <%= link_to 'Back', holidays_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_holiday_path(@holiday), :class => 'btn' %>
  <%= link_to 'Delete', holiday_path(@holiday), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>