config/routes.rb
LunchOrder::Application.routes.draw do

  resources :holidays

  resources :line_items

  get "password_resets/new"
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :categories
  resources :menus
  resources :regions
  resources :departments
  resources :orders
  resources :users do
    collection do
      get 'time_cards'
    end
    member do
      get 'time_card'
      post 'download_time_card'
      get 'edit_password'
      put 'update_password'
      put "request_holiday"
      put "unrequest_holiday"
    end
  end
  resources :work_records do
  collection do
    get 'attendance'
  end
end
  resources :sessions
  resources :password_resets
  root :to => 'sessions#new'
  
  #get 'admin' => 'admin#index'
  
  #get 'logout', to: 'sessions#destroy', as: 'logout'

  
  namespace :admin do
  
    
    root :to => 'sessions#new'
    get "menus/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    resources :categories
    resources :users do
      collection do
        get 'time_cards'
      end
      member do
        get 'time_card'
        post 'download_time_card'
        get 'edit_password'
        put 'update_password'
        put "request_holiday"
        put "unrequest_holiday"
      end
    end
    resources :work_records do
      member do
        post 'approve'
        post 'suspend'
      end
      collection do
        get 'monthly'
      end
    end
    resources :menus do
      member do
        put 'toggle'
      end
    end
    resources :regions
    resources :departments
    resources :orders do
    member do
      get 'approve'
    end
  end
    resources :sessions
    resources :searches
    scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
      resources :menus
      root to: 'menus#index'
    end
    match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
    match '', to: redirect("/#{I18n.default_locale}")
  end 
  
  namespace :kitchen do
    root :to => 'sessions#new'
    get "menus/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    resources :categories
    resources :users
    resources :menus do
      member do
        put 'toggle'
      end
    end
    resources :regions
    resources :orders
    resources :sessions
    resources :searches
  end
  
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :name, :work_start_at, :minute_step, :attendance
  
  has_many :users
  
  validates_uniqueness_of :name
	validates_presence_of :name
	
	def to_param
    "#{id}-#{name.gsub(/\s/,'-')}".parameterize
  end
  
  def work_start_at_to_strf
    self.work_start_at.to_time.strftime("%H:%M") if self.work_start_at.present?
  end
  
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < AdminController
  before_filter :authorize_admin  
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to [:admin,@department], notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to [:admin,@department], notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to admin_departments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  skip_before_filter :authorize_admin
  
  # GET /departments
  # GET /departments.json
  
  # GET /departments/1
  # GET /departments/1.json
  
end  

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/admin/departments/_form.html.erb
<%= simple_form_for [:admin,@department], :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Department</legend>

    <%= f.input :name %>
    <%= f.input :work_start_at, input_html: {class: 'input-mini'} %>
    <%= f.input :minute_step, input_html: {class: 'input-mini'} %>
	<%= f.input :attendance, :label => 'Part-Time Attendance', :as => :select,  :collection => ['No', 'Yes' ], :selected => params[0] %>
	
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_departments_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/admin/departments/index.html.erb
<h1><%= t "departments.title" %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Work Starts at</th>
      <th>Minute Step</th>
      <th>Part-Time Attendance</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.id %></td>
        <td><%= link_to department.name, department_path(department) %></td>
		<td><%= department.work_start_at_to_strf %></td>        
		<td><%= department.minute_step %></td>        
		<td><%= department.attendance %></td>        
        <td>
          <%= link_to (t "orders.edit"), edit_admin_department_path(department), :class => 'btn btn-mini' %>
          <%= link_to (t "orders.destroy"), admin_department_path(department), :method => :delete, :confirm => 'Are you sure?', :style => 'color: white', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<b><%= t "departments.total" %> <%= Department.count %></b><br/><br/>

<%= link_to (t "orders.new"), new_admin_department_path, :style => 'color: white', :class => 'btn btn-primary' %>

app/views/admin/departments/new.html.erb
<%= render 'form' %>

app/views/admin/departments/show.html.erb
<h2>Department</h2>

<p>
  <b>Name</b><br>
  <%= @department.name %>
</p>


<div class="form-actions">
  <%= link_to 'Back', admin_departments_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_admin_department_path(@department), :class => 'btn' %>
  <%= link_to 'Delete', admin_department_path(@department), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>