config/routes.rb
LunchOrder::Application.routes.draw do

  resources :holidays

  resources :line_items

  get "password_resets/new"
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :categories
  resources :menus
  resources :regions
  resources :departments
  resources :orders
  resources :users do
    collection do
      get 'time_cards'
    end
    member do
      get 'time_card'
      post 'download_time_card'
      get 'edit_password'
      put 'update_password'
      put "request_holiday"
      put "unrequest_holiday"
    end
  end
  resources :work_records do
  collection do
    get 'attendance'
  end
end
  resources :sessions
  resources :password_resets
  root :to => 'sessions#new'
  
  #get 'admin' => 'admin#index'
  
  #get 'logout', to: 'sessions#destroy', as: 'logout'

  
  namespace :admin do
  
    
    root :to => 'sessions#new'
    get "menus/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    resources :categories
    resources :users do
      collection do
        get 'time_cards'
      end
      member do
        get 'time_card'
        post 'download_time_card'
        get 'edit_password'
        put 'update_password'
        put "request_holiday"
        put "unrequest_holiday"
      end
    end
    resources :work_records do
      member do
        post 'approve'
        post 'suspend'
      end
      collection do
        get 'monthly'
      end
    end
    resources :menus do
      member do
        put 'toggle'
      end
    end
    resources :regions
    resources :departments
    resources :orders do
    member do
      get 'approve'
    end
  end
    resources :sessions
    resources :searches
    scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
      resources :menus
      root to: 'menus#index'
    end
    match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
    match '', to: redirect("/#{I18n.default_locale}")
  end 
  
  namespace :kitchen do
    root :to => 'sessions#new'
    get "menus/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    resources :categories
    resources :users
    resources :menus do
      member do
        put 'toggle'
      end
    end
    resources :regions
    resources :orders
    resources :sessions
    resources :searches
  end
  
end

app/models/work_record.rb
class WorkRecord < ActiveRecord::Base
  attr_accessible :work_on, :start_at,:end_at,:lunch_start_at,:lunch_end_at,
                  :wage,:user_id,:approved_by, :state,:department, :department_id,
                  :attend_at,:left_at
  
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  #belongs_to :approved_by, :class_name => "User", :foreign_key => "user_id"
  belongs_to :department, :class_name => "Department", :foreign_key => "department_id"
  
  validates_presence_of :user_id, :work_on
  validates_uniqueness_of :work_on, scope: :user_id
  
  state_machine :initial => :not_attend do

    state :not_attend, :attended, :left, :approved, :pending
    
    event :attend do
      transition :from => [:not_attend, :pending],  :to => :attended
    end

    event :leave do
      transition :from => [:attended, :pending],  :to => :left
    end
    
    event :approve do
      transition :from => [:left, :pending],  :to => :approved
    end
    
    event :suspend do
      transition :from => [:not_attend, :attended, :left, :approved, :pending],  :to => :pending
    end
    
    before_transition :to => :attended do |wr|
      st = wr.try(:user).try(:department).try(:work_start_at)
      nt = Time.now
      wr.attend_at  = nt
      if st.present?
        wr.start_at   = (st.hour*60+st.min) < (nt.hour*60+nt.min) ? wr.start_time : st
      else
        wr.start_at   = wr.start_time
      end
    end

    before_transition :to => :left do |wr|
      wr.end_at = wr.end_time
      wr.left_at = Time.now
    end
    
  end

  scope :approved, where(:state => 'approved')
  scope :not_approved, where("work_records.state != 'approved'")
  scope :pending, where(:state => 'pending')
  scope :b_user, lambda { |uid|
    where("work_records.user_id = ?", uid) 
  }
  scope :b_dept, lambda { |did|
    where("work_records.department_id = ?", did).
    order("work_records.user_id")    
  }
  scope :monthly, lambda { |date|
    where("work_records.work_on >= '#{Time.gm(date.to_date.year,date.to_date.months_ago(1).month,21,0,0,0).to_s(:db)}' and work_records.work_on <= '#{Time.gm(date.to_date.year,date.to_date.month,20,23,59,59).to_s(:db)}'"). 
    order("work_records.work_on")
  }
  scope :daily, lambda { |date|
    where("work_records.work_on = '#{date.to_date.to_s(:db)}'")
  }

  

  def attend_at_to_strf
    begin
      self.attend_at.to_time.strftime("%H:%M")
    rescue
      ""
    end
  end
    
  def start_at_to_strf
    begin
      self.start_at.to_time.strftime("%H:%M")
    rescue
      ""
    end
  end

  def end_at_to_strf
    begin
      self.end_at.to_time.strftime("%H:%M")
    rescue
      ""
    end
  end
  
  def lunch_hours
    begin
      min = self.lunch_end_at - self.lunch_start_at
      min.divmod(60)[0].to_s + " mins"
    rescue
      "-"
    end
  end
  
  def daily_work_time
    #days = (self.end_at - self.start_at).divmod(24*60*60)
    #hours = days[1].divmod(60*60)
    #mins = hours[1].divmod(60)  
    begin
      x = ((end_h - sta_h) - (lend_h - lsta_h)).quo(60).to_f
    rescue
      x = 0
    end
    x < 0 ? 0 : x
  end
  
  def end_h
    begin
      (self.end_at.hour*60)+((self.end_at.min/15)*15)
    rescue
      0
    end
  end
    
  def sta_h
    begin
      (self.start_at.hour*60)+((ceil15(self.start_at.min)/15)*15)
    rescue
      0
    end
  end
  
  def lend_h
    begin
      (self.lunch_end_at.hour*60)+((self.lunch_end_at.min/15)*15)
    rescue
      0
    end
  end
  
  def lsta_h
    begin
      (self.lunch_start_at.hour*60)+((self.lunch_start_at.min/15)*15)
    rescue
      0
    end
  end

  def start_time
    begin
      t = Time.now
      m = ceil15(t.min)
      h = m.zero? ? t.hour+1 : t.hour
      [h,m,0].join(":")
    rescue
      t
    end    
  end

  def end_time
    begin
      t = Time.now
      [t.hour,((t.min/15)*15),0].join(":")
    rescue
      t
    end
  end

  private

  def ceil15(min)
    case min
    when 1..15
      15
    when 16..30
      30
    when 31..45
      45
    else
      0
    end
  end
end

app/controllers/admin/work_records_controller.rb
class Admin::WorkRecordsController < AdminController
  before_filter :authorize_admin  
  
  def index
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @work_records = WorkRecord.b_dept(current_user.department_id).daily(@date)
  end

  def new
    @work_record = WorkRecord.new
  end

  def create
    @work_record = WorkRecord.new(params[:work_record])
    
    respond_to do |format|
      if @work_record.save
        format.html { redirect_to @work_record }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end    
  end

  def edit
    @work_record = WorkRecord.find(params[:id])
  end

  def update
    @work_record = WorkRecord.find(params[:id])

    respond_to do |format|
      if @work_record.update_attributes(params[:work_record])
        format.html { redirect_to work_records_path }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  def destroy
    @work_record = WorkRecord.find(params[:id])
    @work_record.destroy

    #redirect_to root_path
  end
  
  def approve
    @work_record = WorkRecord.find(params[:id])
    @work_record.approved_by = current_user.id
    @work_record.approve!
  end
  
  def suspend
    @work_record = WorkRecord.find(params[:id])
    @work_record.approved_by = nil
    @work_record.suspend!
  end
  
  def monthly
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @users = User.b_dept(current_user.department_id).where("users.kind = ?", "Part-Time Staff") 
  end
end

app/controllers/work_records_controller.rb
class WorkRecordsController < ApplicationController
  before_filter :authorize
  
  def index
  
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @work_records = WorkRecord.where('user_id' => current_user.id).monthly(@date)

  end

  
  def attendance

      @today        = Time.now
      @work_record  = current_user.todays_work_record
    
      if @work_record.blank?
        @work_record  = current_user.work_records.build(
                      :work_on        => @today,
                      :wage           => current_user.wage,
                      :department_id  => current_user.department_id)
      
      elsif @work_record.attended?
        @ls = Time.gm(@today.year,@today.month,@today.day,13,00,0)
        @le = @ls + 45.minutes
        @step = current_user.try(:department).try(:minute_step).to_i
      end      

  end
  
  
  def create
    @user = User.find(current_user.id)
    redirect_to root_path, alert: t('alert.spoof') if spoof?
    begin
      @work_record = @user.work_records.build(params[:work_record])
      @work_record.attend!
      msg = t('user_work_records.create.success')
    rescue
      msg = t('commons.error')
    end
    redirect_to attendance_work_records_path, notice: msg
  end
  
  def update
    @user = User.find(current_user.id)
    redirect_to root_path, alert: t('alert.spoof') if spoof?
    @work_record = WorkRecord.find(params[:id])
    
    if @work_record.update_attributes(params[:work_record])
      begin
        @work_record.leave!
        msg = t('user_work_records.leave.success')
      rescue
        msg = t('commons.error')
      end
    else
      msg = t('commons.error')
    end
    redirect_to attendance_work_records_path, notice: msg
  end
  
  def spoof?
    @user != current_user
  end

end

app/helpers/work_records_helper.rb
module WorkRecordsHelper
    
  def time_strftime(t)
    begin
      t.to_time.strftime("%H:%M")
    rescue
      "-"
    end
  end
    
	def show_wr_status(obj)
		case obj.state
		when 'not_attend'
			content_tag :span, obj.human_state_name.capitalize, class: 'label label-inverse'
		when 'attended'
			content_tag :span, obj.human_state_name.capitalize, class: 'label label-info'
		when 'left'
			content_tag :span, obj.human_state_name.capitalize, class: 'label'
		when 'approved'
			content_tag :span, obj.human_state_name.capitalize, class: 'label label-success'
		when 'pending'
			content_tag :span, obj.human_state_name.capitalize, class: 'label label-warning'
		else
			content_tag :span, "ERROR", class: 'label label-important'
		end
	end

	def show_lunch_min(wr)
		begin
			min = wr.lunch_end_at - wr.lunch_start_at
			min.divmod(60)[0].to_s + "mins"
		rescue
			"-"
		end
	end

end

app/views/admin/work_records/_form.html.erb
<%= simple_form_for @work_record, :html => { :class => 'form-horizontal' } do |f| %>
	<%= f.input :attend_at if @work_record.attend_at.present? %>
  <%= f.input :start_at, minute_step: current_user.try(:department).try(:minute_step).to_i if @work_record.start_at.present? %>
  <%= f.input :lunch_start_at, minute_step: current_user.try(:department).try(:minute_step).to_i if @work_record.lunch_start_at.present? %>
  <%= f.input :lunch_end_at, minute_step: current_user.try(:department).try(:minute_step).to_i if @work_record.lunch_end_at.present? %>
	<%= f.input :end_at,minute_step: current_user.try(:department).try(:minute_step).to_i if @work_record.end_at.present? %>
  <%= f.input :wage %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                work_records_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/work_records/_jsform.html.erb
<div class="modal-header">
  <button class="close" data-dismiss="modal">&times;</button>
  <h3>Edit</h3>
</div>
<div class="modal-body">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= raw(msg) %>
    </div>
  <% end %>

  <%= simple_form_for [:admin,@work_record], :html => { :class => 'form-horizontal', remote: true } do |f| %>
    <%= f.input :state, collection: ['attended', 'left', 'approved', 'pending'] %>
    <%= f.input :attend_at, input_html: {class: 'input-small'} %>
    <%= f.input :start_at, input_html: {class: 'input-small'}, minute_step: current_user.try(:department).try(:minute_step).to_i %>
    <%= f.input :lunch_start_at, input_html: {class: 'input-small'}, minute_step: current_user.try(:department).try(:minute_step).to_i %>
    <%= f.input :lunch_end_at, input_html: {class: 'input-small'}, minute_step: current_user.try(:department).try(:minute_step).to_i %>
    <%= f.input :end_at, minute_step: current_user.try(:department).try(:minute_step).to_i, input_html: {class: 'input-small'} %>
    <%= f.input :left_at, input_html: {class: 'input-small'} %>
  <div class="form-actions">
    <%= f.submit "Submit", :class => 'btn btn-primary' %>
    <a href="#" class="btn" data-dismiss="modal" ><%= t('helpers.links.cancel')%></a>
  </div>

  <% end %>
  
  
</div>
<div class="modal-footer">
</div>

app/views/admin/work_records/_njsform.html.erb
<div class="modal-header">
  <button class="close" data-dismiss="modal">&times;</button>
  <h3>Edit</h3>
</div>
<div class="modal-body">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= raw(msg) %>
    </div>
  <% end %>

  <%= simple_form_for [:admin,@work_record], :html => { :class => 'form-horizontal', remote: true } do |f| %>
    <%= f.input :user_id, collection: current_user.department.users.map{|x| [x.name,x.id]} %>
    <%= f.input :state, collection: ['attended', 'left', 'approved', 'pending'] %>
    <%= f.input :work_on,input_html: {class: 'input-small'},order: [:day, :month, :year] %>
    <%= f.input :attend_at, input_html: {class: 'input-small'} %>
    <%= f.input :start_at, input_html: {class: 'input-small'}, minute_step: current_user.try(:department).try(:minute_step).to_i %>
    <%= f.input :lunch_start_at, input_html: {class: 'input-small'}, minute_step: current_user.try(:department).try(:minute_step).to_i %>
    <%= f.input :lunch_end_at, input_html: {class: 'input-small'}, minute_step: current_user.try(:department).try(:minute_step).to_i %>
    <%= f.input :end_at, input_html: {class: 'input-small'} %>
    <%= f.hidden_field :department_id, value: current_user.department_id %>
  <div class="form-actions">
    <%= f.submit "Submit", :class => 'btn btn-primary' %>
    <a href="#" class="btn" data-dismiss="modal" ><%= t('helpers.links.cancel')%></a>
  </div>

  <% end %>
  
  
</div>
<div class="modal-footer">
</div>

app/views/admin/work_records/_work_record.html.erb
<td><%= work_record.user.name %></td>
<td><%= show_wr_status(work_record) %></td>
<td><%= time_strftime work_record.start_at %></td>
<td><%= time_strftime work_record.lunch_start_at %></td>
<td><%= time_strftime work_record.lunch_end_at %></td>
<td><%= time_strftime work_record.end_at %></td>
<td><%= work_record.daily_work_time %></td>
<td><%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_admin_work_record_path(work_record), :class => 'btn btn-mini',remote: true %>&nbsp;
    <%= link_to t('helpers.links.approve'), approve_admin_work_record_path(work_record), {class: 'btn btn-mini btn-warning', remote: true,method: :post} if work_record.left? || work_record.pending? %>
    <%= link_to t('helpers.links.suspend'), suspend_admin_work_record_path(work_record), class: 'btn btn-mini', method: :post, remote: true if work_record.approved? %>
    <%= link_to t('helpers.links.destroy'), work_record_path(work_record), class: 'btn btn-mini btn-danger', method: :delete, remote: true, confirm: "Are you sure?" %>    
</td>

app/views/admin/work_records/approve.js.erb
$("tr#wr_<%= @work_record.id %>").html("<%= j(render(:partial => 'work_record',:object => @work_record)) %>");

app/views/admin/work_records/create.js.erb
<% if @work_record.errors.present? %>
	$("div#myModal").html("<%= j(render(:partial => 'njsform')) %>");
<% else %>
	$("div#myModal").modal('hide');
	$("tbody#work_records").append("<tr id='wr_<%= @work_record.id %>'><%= j(render(:partial => 'work_record',:object => @work_record)) %></tr>");
<% end -%>

app/views/admin/work_records/destroy.js.erb
$("tr#wr_<%= @work_record.id %>").hide()

app/views/admin/work_records/edit.html.erb
<%- model_class = WorkRecord -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/work_records/edit.js.erb
$("div#myModal").modal().html("<%= j render(:partial => 'jsform') %>");

app/views/admin/work_records/index.html.erb
<%- model_class = WorkRecord -%>
<div class="page-header">
  <h2 style="text-align:center;">
		<%= link_to "<", date: @date.yesterday %>
    <%= @date.strftime("%d %b %a") %>
    <%= link_to ">", date: @date.tomorrow %>    
	</h2>
</div>
<%= %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('simple_form.labels.work_record.user') %></th>
			<th><%= t('simple_form.labels.work_record.state') %></th>
      <th><%= t('simple_form.labels.work_record.start_at') %></th>
      <th><%= t('simple_form.labels.work_record.lunch_start_at') %></th>
      <th><%= t('simple_form.labels.work_record.lunch_end_at') %></th>
			<th><%= t('simple_form.labels.work_record.end_at') %></th>
			<th><%= t('simple_form.labels.work_record.work_hours') %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody id="work_records">
    <% @work_records.each do |work_record| %>
      <tr id="wr_<%= work_record.id %>">
        <%= render partial: 'work_record', object: work_record %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t('.new'), new_admin_work_record_path, :style => 'color: white',
            :class => 'btn btn-primary', remote: true %>

app/views/admin/work_records/monthly.html.erb
<%- model_class = WorkRecord -%>
<div class="page-header">
  <h2 style="text-align:center;">
	  <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>
	</h2>
</div>
<%= %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('simple_form.labels.work_record.user') %></th>
			<th>Not Approved</th>
      <th>Approved</th>
      <th>Total Hours</th>
      <th>Total</th>
			<th>Download</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
				<td><%= pluralize(WorkRecord.monthly(@date).b_user(user.id).not_approved.length,'day') %></td>
				<td><%= pluralize(WorkRecord.monthly(@date).b_user(user.id).approved.length,'day') %></td>
				<td><%= pluralize(WorkRecord.monthly(@date).b_user(user.id).approved.inject(0){|sum,x| sum + x.daily_work_time},'hour') %></td>
        <td><%= WorkRecord.monthly(@date).b_user(user.id).approved.inject(0){|sum,x| sum + x.daily_work_time*x.wage}.to_money.format %></td>
				<td><%= link_to t('nav.timecard'), download_time_card_admin_user_path(user,:year => @date.year,:month => @date.month), :style => 'color: white', method: :post, class: "btn btn-mini btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/work_records/new.js.erb
$("div#myModal").modal().html("<%= j render(:partial => 'njsform') %>");

app/views/admin/work_records/suspend.js.erb
$("tr#wr_<%= @work_record.id %>").html("<%= j(render(:partial => 'work_record',:object => @work_record)) %>");

app/views/admin/work_records/update.js.erb
<% if @work_record.errors.present? %>
	$("div#myModal").html("<%= j(render(:partial => 'jsform')) %>");
<% else %>
	$("div#myModal").modal('hide');
	$("tr#wr_<%= @work_record.id %>").html("<%= j(render(:partial => 'work_record',:object => @work_record)) %>");
<% end -%>