config/routes.rb
LunchOrder::Application.routes.draw do

  resources :holidays

  resources :line_items

  get "password_resets/new"
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :categories
  resources :menus
  resources :regions
  resources :departments
  resources :orders
  resources :users do
    collection do
      get 'time_cards'
    end
    member do
      get 'time_card'
      post 'download_time_card'
      get 'edit_password'
      put 'update_password'
      put "request_holiday"
      put "unrequest_holiday"
    end
  end
  resources :work_records do
  collection do
    get 'attendance'
  end
end
  resources :sessions
  resources :password_resets
  root :to => 'sessions#new'
  
  #get 'admin' => 'admin#index'
  
  #get 'logout', to: 'sessions#destroy', as: 'logout'

  
  namespace :admin do
  
    
    root :to => 'sessions#new'
    get "menus/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    resources :categories
    resources :users do
      collection do
        get 'time_cards'
      end
      member do
        get 'time_card'
        post 'download_time_card'
        get 'edit_password'
        put 'update_password'
        put "request_holiday"
        put "unrequest_holiday"
      end
    end
    resources :work_records do
      member do
        post 'approve'
        post 'suspend'
      end
      collection do
        get 'monthly'
      end
    end
    resources :menus do
      member do
        put 'toggle'
      end
    end
    resources :regions
    resources :departments
    resources :orders do
    member do
      get 'approve'
    end
  end
    resources :sessions
    resources :searches
    scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
      resources :menus
      root to: 'menus#index'
    end
    match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
    match '', to: redirect("/#{I18n.default_locale}")
  end 
  
  namespace :kitchen do
    root :to => 'sessions#new'
    get "menus/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    resources :categories
    resources :users
    resources :menus do
      member do
        put 'toggle'
      end
    end
    resources :regions
    resources :orders
    resources :sessions
    resources :searches
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :name, :email, :password, :password_confirmation, :kind, :ni_number, :wage, :holiday_request, :admin, 
  :department, :department_id, :department_name, :department_attendance, :holiday

  validate :wage_for_part
  
  validates_presence_of  :email, :name
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Invalid email"
  validates_length_of :name, :within => 3..40
  validates_uniqueness_of :email
  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :password_confirmation, on: :create
 
  before_create { generate_token(:auth_token) }
  
  belongs_to :department
  has_many :assignments
  has_many :holiday
  has_many    :work_records, order: 'work_on'
  has_one     :todays_work_record,  :class_name => "WorkRecord", conditions: "work_records.work_on = '#{Date.today.to_s(:db)}'"
  
  
  scope :administrators, where("assignments.role_id = 1").joins(:assignments)
  scope :customers, where("assignments.role_id IS NULL").includes(:assignments)
  
  
#  state_machine :initial => :active, :use_transactions => false do

 #   state :active,:inactive
    
  #  event :activate do
#      transition :from => :inactive,  :to => :active
 #   end

#    event :inactivate do
#      transition :from => :active,  :to => :inactive
#    end

#  end

  def wage_for_part	  
   if self.kind == "Part-Time Staff" && self.wage == nil
      self.errors.add(:kind, "Wage is required for part-time staff")
   end
  end
  
  scope :active, where(:state => 'active')
  scope :inactive, where(:state => 'inactive')
  #scope :staffs, where("is_admin != 1 and is_proper != 1")
  scope :b_dept, lambda { |did|
    where("users.department_id = ?", did) 
  }
  
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def department_name
    department.try(:name)
  end

  def department_name=(name)
    self.department = Department.find_or_create_by_name(name) if name.present?
  end
  
  def holiday_date
    holiday.try(:holiday)
  end

  def holiday_date=(holiday)
    self.holiday = Holiday.find_or_create_by_holiday(holiday) if holiday.present?
  end
  
  def department_attendance
    department.try(:attendance)
  end

  def department_attendance=(attendance)
    self.department = Department.find_or_create_by_attendance(attendance) if attendance.present?
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
before_filter :authorize_admin  
  
  def index

    @users = User.order("name").page(params[:page]).per(20)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
  
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end
	
	def edit
    @user = User.find(params[:id])
  end
	
	def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin,@user], notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to [:admin,@user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
  
  def time_cards
    @users = User.active
  end
  
  def time_card
    @user = User.find(params[:id])
  end
  
  def download_time_card
    @user = User.find(params[:id])
    date  = params[:date][:year].to_s + "/" + params[:date][:month].to_s + "/01" if params[:date].present?
    date  = params[:year].to_s + "/" + params[:month].to_s + "/01" if date.blank?
    @date = Date.parse(date)
    @work_records = WorkRecord.approved.b_user(@user.id).monthly(@date)
    @total_hours = 0
    @total_pay = 0
    @holidays = Holiday.where('holiday' => date).where('user_id' => @user.id)
  
    data = CSV.generate do |csv|
      csv << ["Holiday"] if @holidays.size > 0 
      csv << ["DATE","START TIME","LUNCH","END TIME","TOTAL HOURS","HOURS	RATE x HOURS"]
      @work_records.each do |wr|
        @total_hours += wr.daily_work_time
        @total_pay += wr.daily_work_time * wr.wage
        csv << [wr.work_on,wr.start_at_to_strf,wr.lunch_hours,wr.end_at_to_strf,wr.daily_work_time,(wr.daily_work_time * wr.wage)]
      end
      csv << ["","","","",@total_hours,@total_pay]
    end
    if @work_records.present?
      send_data(data, type: 'text/csv', filename: "Time_Card_#{@user.name}_#{@date.to_time.strftime('%Y_%B')}.csv") 
    else
      redirect_to :back
    end
  end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize_admin
  
  
  def new
	  @user = User.new
	end
	
	def create
	  @user = User.new(params[:user])
	  if @user.save
	    cookies[:auth_token] = @user.auth_token
	    redirect_to root_url, :notice => "Signed up!"
	    redirect_to offers_path
	  else
	    render "new"
	  end
	end
	
	def request_holiday
	  User.where('id' => current_user).update_all(:holiday_request => true)
#  	current_user.update_attributes(holiday_request: true)
  	redirect_to :back
  end

  def unrequest_holiday
	  User.where('id' => current_user).update_all(:holiday_request => false)
  	redirect_to :back
  end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin,@user], :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> User</legend>

    <%= f.input :name, :label => 'Full Name' %>
	<%= f.input :email %>
	<% if params[:action] == 'new' || params[:action] == 'create' %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <% end -%>
	<%= f.input :department_id, :label => 'Department', :as => :select, :collection => 		Department.all.map{|d| ["#{d.name}", d.id]}, :include_blank => false  %>
	<%= f.input :kind, :input_html => { :id => "select" }, :collection => ['Full-Time Staff', 'Part-Time Staff', 'Kitchen', 'Admin'], :selected => params[0]  %>
	<div id ="extra" style="display:none;" >
	<%= f.input :ni_number %>	
	<%= f.input :wage %>
	</div>
		
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_users_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1><%= t "users.title" %></h1>
<%= paginate @users %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Full Name</th>
      <th>Email</th>
 	  <th>Department</th>
	  <th>Type</th>
	  <th>Wage</th>
	  <th>Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.name, admin_user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.department_name %></td>
		<td><%= user.kind %></td>
		<td><%= if user.wage != nil 
			user.wage.to_money.format 
			end %></td>
        <td>
          <%= link_to (t "orders.edit"), edit_admin_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to (t "orders.destroy"), admin_user_path(user), :method => :delete, :confirm => 'Are you sure?', :style => 'color: white', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
	<b><%= t "users.total" %>	<%= User.count %></b><br/><br/>
<%= link_to (t "orders.new"), new_admin_user_path, :style => 'color: white', :class => 'btn btn-primary' %>

app/views/admin/users/show.html.erb
<h1>User</h1>

<p>
  <b>Name</b><br>
  <%= @user.name %>
</p>


<div class="form-actions">
  <%= link_to 'Back', admin_users_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_admin_user_path(@user), :class => 'btn' %>
  <%= link_to 'Delete', admin_user_path(@user), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>